name: Build and Update on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout application_repo
        uses: actions/checkout@v2
        with:
          repository: susrk/application_repo

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}

      - name: Checkout Gitops repository
        uses: actions/checkout@v2
        with:
          repository: susrk/Gitops
          token: ${{ secrets.GITHUB_TOKEN }}
          path: Gitops

      - name: Update details in Gitops repository
        run: |
          echo "Updating details in Gitops repository..."
          echo "Image: ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}" > Gitops/image-info.txt
          
      - name: Commit and push changes
        run: |
          cd Gitops
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update image details from PR #${{ github.event.number }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
